title: Site2
description: Short description about your site's purpose site2
author:
  name: Serhii Ilin
  email: serhii.ilin@gmail.com
theme: minima
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
#    - { platform: github,  user_url: "https://github.com/jekyll/jekyll" }
#    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }
#    - { platform: linkedin, user_url: "https://linkedin.com/jekyllrb" }    
#    - { platform: telegram, user_url: "https://linkedin.com/jekyllrb" }    
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
show_downloads: false
header_pages:
  - portfolio.md
  - about.md
#google_analytics: UA-NNNNNNNN-N
#show_excerpts: false
