# remote_theme: pages-themes/minimal@v0.2.0
theme: minima
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/jekyll/jekyll" }
    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }
    - { platform: linkedin, user_url: "https://linkedin.com/jekyllrb" }    
    - { platform: telegram, user_url: "https://linkedin.com/jekyllrb" }    
plugins:
#  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
  - jekyll-seo-tag
title: [Site2]
description: [A short description of your site's purpose site2]
show_downloads: false
header_pages:
  - about.md
  - portfolio.md
google_analytics: UA-NNNNNNNN-N
# show_excerpts: false
